#!/usr/bin/env python3
"""
Neo4j MCP Gateway Client

Tests the Neo4j MCP server via AgentCore Gateway.
Uses credentials from .mcp-credentials.json (generated by ./deploy.sh credentials).

Usage:
    python gateway_client.py test              # Run full test suite
    python gateway_client.py tools             # List available tools
    python gateway_client.py schema            # Get Neo4j schema
    python gateway_client.py query             # Run test query

Prerequisites:
    Run './deploy.sh credentials' to generate .mcp-credentials.json
"""

import asyncio
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from mcp_operations import (
    connect_and_run,
    run_full_tests,
    list_tools,
    get_schema,
    run_query,
)


# =============================================================================
# Credentials
# =============================================================================

CREDENTIALS_FILE = Path(__file__).parent.parent / ".mcp-credentials.json"


def load_credentials() -> dict:
    """Load credentials from .mcp-credentials.json."""
    if not CREDENTIALS_FILE.exists():
        print("ERROR Credentials file not found: .mcp-credentials.json")
        print()
        print("Run './deploy.sh credentials' to generate it")
        sys.exit(1)

    with open(CREDENTIALS_FILE) as f:
        return json.load(f)


def check_token_expiry(credentials: dict) -> bool:
    """Check if the token is expired. Returns True if valid."""
    expires_at_str = credentials.get("token_expires_at")
    if not expires_at_str:
        return False

    try:
        expires_at = datetime.fromisoformat(expires_at_str)
        now = datetime.now(timezone.utc)
        # Add 5 minute buffer
        return now < expires_at
    except (ValueError, TypeError):
        return False


def get_credentials() -> dict:
    """Get credentials, checking for expiry."""
    credentials = load_credentials()

    if not check_token_expiry(credentials):
        print("WARN  Token has expired")
        print()
        print("Run './deploy.sh credentials' to refresh")
        sys.exit(1)

    return credentials


# =============================================================================
# Commands
# =============================================================================


def cmd_token():
    """Display the current token from credentials file."""
    print("=" * 70)
    print("MCP Credentials")
    print("=" * 70)
    print()

    credentials = load_credentials()

    print(f"Gateway URL: {credentials.get('gateway_url')}")
    print(f"Client ID:   {credentials.get('client_id')}")
    print(f"Scope:       {credentials.get('scope')}")
    print(f"Expires At:  {credentials.get('token_expires_at')}")
    print()

    if check_token_expiry(credentials):
        print("Status: VALID")
    else:
        print("Status: EXPIRED - run './deploy.sh credentials' to refresh")
        sys.exit(1)

    print()
    print("=" * 70)
    print("Access Token:")
    print("=" * 70)
    print()
    print(credentials.get("access_token"))
    print()


async def cmd_mcp_operation(operation, operation_name: str):
    """Run an MCP operation via the Gateway."""
    print("=" * 70)
    print(f"Neo4j MCP Gateway - {operation_name}")
    print("=" * 70)
    print()

    # Load credentials from file
    print("INFO  Loading credentials from .mcp-credentials.json...")
    credentials = get_credentials()

    gateway_url = credentials.get("gateway_url")
    access_token = credentials.get("access_token")

    print(f"INFO  Gateway URL: {gateway_url}")
    print(f"INFO  Token expires: {credentials.get('token_expires_at')}")
    print()

    # Connect to Gateway
    print("Connecting to Neo4j MCP Gateway...")
    print("Initializing MCP session...")

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
    }

    try:
        await connect_and_run(gateway_url, operation, headers=headers)
    except Exception as e:
        print(f"ERROR Connection failed: {e}")
        sys.exit(1)


def show_help():
    """Show help message."""
    print("""Neo4j MCP Gateway Client

Target: AgentCore Gateway
Auth:   Uses .mcp-credentials.json (generated by ./deploy.sh credentials)

Usage: python gateway_client.py <command>

Commands:
  test    Run full test suite
  tools   List available MCP tools
  schema  Get Neo4j database schema
  query   Run a test query (node counts by label)
  token   Show current token and expiry status
  help    Show this help message

Prerequisites:
  Run './deploy.sh credentials' to generate .mcp-credentials.json

Note: Tool names are prefixed with the target name when accessed via Gateway.
      For example: neo4j-mcp-server-target___read-cypher

Examples:
  ./deploy.sh credentials    # Generate credentials file first
  python gateway_client.py test
  python gateway_client.py tools
""")


def main():
    if len(sys.argv) < 2 or sys.argv[1] in ("help", "--help", "-h"):
        show_help()
        sys.exit(0)

    command = sys.argv[1]

    # Token command doesn't need async
    if command == "token":
        cmd_token()
        return

    # MCP operations
    operations = {
        "test": ("Gateway Test", run_full_tests),
        "tools": ("List Tools", list_tools),
        "schema": ("Get Schema", get_schema),
        "query": ("Run Query", run_query),
    }

    if command not in operations:
        print(f"Unknown command: {command}")
        print("Run 'python gateway_client.py help' for usage")
        sys.exit(1)

    operation_name, operation = operations[command]
    asyncio.run(cmd_mcp_operation(operation, operation_name))


if __name__ == "__main__":
    main()
