#!/bin/bash
# ==============================================================================
# CLOUD.SH - Neo4j MCP Gateway Testing Script
# ==============================================================================
#
# PURPOSE:
#   Tests the Neo4j MCP server via AgentCore Gateway. Uses credentials from
#   .mcp-credentials.json (generated by ./deploy.sh credentials).
#
# PREREQUISITES:
#   Run './deploy.sh credentials' first to generate .mcp-credentials.json
#
# TARGET:
#   AgentCore Gateway (endpoint from credentials file)
#
# AUTHENTICATION:
#   Uses pre-generated JWT token from .mcp-credentials.json
#   Token expires after ~1 hour - refresh with './deploy.sh credentials'
#
# COMMANDS:
#   (none)    Run full test suite
#   token     Show current token and expiry status
#   tools     List available MCP tools
#   schema    Get Neo4j database schema
#   query     Run a test query (node counts by label)
#
# EXAMPLES:
#   ./deploy.sh credentials  # Generate credentials first
#   ./cloud.sh               # Run full test suite
#   ./cloud.sh token         # Check token status
#   ./cloud.sh tools         # List available tools
#
# NOTE:
#   Tool names are prefixed with target name when accessed via Gateway.
#   Example: neo4j-mcp-server-target___read-cypher
#
# SEE ALSO:
#   ./local.sh      - Local Docker server testing (no auth)
#   ./cloud-http.sh - Raw HTTP debugging (direct Runtime access)
#
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check for credentials file
check_credentials() {
    if [[ ! -f "$SCRIPT_DIR/.mcp-credentials.json" ]]; then
        echo "ERROR: Credentials file not found: .mcp-credentials.json"
        echo ""
        echo "Run './deploy.sh credentials' to generate it"
        exit 1
    fi
}

# Setup Python virtual environment if needed
setup_venv() {
    if [[ ! -d "$SCRIPT_DIR/.venv" ]]; then
        echo "INFO  Setting up Python virtual environment..."
        python3 -m venv "$SCRIPT_DIR/.venv"
        source "$SCRIPT_DIR/.venv/bin/activate"
        pip install --quiet --upgrade pip
        pip install --quiet mcp httpx
        echo "OK    Virtual environment ready"
        echo ""
    else
        source "$SCRIPT_DIR/.venv/bin/activate"
    fi
}

# Map empty command to 'test' for backwards compatibility
command="${1:-test}"

# Help doesn't need venv or credentials
if [[ "$command" == "help" || "$command" == "--help" || "$command" == "-h" ]]; then
    python3 "$SCRIPT_DIR/client/gateway_client.py" help
    exit 0
fi

# Check credentials exist
check_credentials

# Setup venv and run
setup_venv
python3 "$SCRIPT_DIR/client/gateway_client.py" "$command"
